apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-skt2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-skt2@sha256:db7c7d5c14ee302023793f5a3e80ca8bea703f90d618aaf80e562a5a47672aca
        name: my-nodejs
        resources: {}
status: {}
